# Generated by Django 5.2.8 on 2026-06-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='exprience_level',
            new_name='experience_level',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='ower_name',
            new_name='owner_name',
        ),
    ]
